[package]
name = "tokio-sty"
version = "0.1.0"
edition = "2024"

[dependencies]
futures ={version = "0.3.31",features = ["std","alloc"]}
reqwest = {version = "0.12.15",features = ["json","stream"]}
serde = {version = "1.0.219",features = ["derive"]}
tokio = { version = "1.0", features = ["full"] }
